[project]
name = "athena"
version = "0.1.0"
description = "ATHENA – Automated Transformations Highlighted and Explained Nicely and Accurately."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
